[default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
remappings = [
    '@optyfi/defi-legos/=lib/defi-legos/src/',
    'forge-std/=lib/forge-std/src/'
]
optimizer = true
optimizer_runs = 200
test = "test/foundry"

# See more config options https://github.com/gakonst/foundry/tree/master/config