/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StrategyManagerV2 } from "./StrategyManagerV2";
export { StrategyManagerV2__factory } from "./factories/StrategyManagerV2__factory";
