export default {
  SETUP: {
    NAME: "setup",
    DESCRIPTION: "Deploy Registry, HarvestCodeProvider and Adapter contracts and setup all necessary actions",
  },
  DEPLOYMENT_TASKS: {
    DEPLOY_ERC20: { NAME: "deploy-erc20", DESCRIPTION: "Deploy ERC20" },
    DEPLOY_ADAPTER: { NAME: "deploy-adapter", DESCRIPTION: "Deploy Adapter contract" },
    DEPLOY_ADAPTERS: { NAME: "deploy-adapters", DESCRIPTION: "Deploy Adapter contracts" },
    DEPLOY_HARVEST_CODE_PROVIDER: { NAME: "deploy-harvest-code-provider", DESCRIPTION: "Deploy Harvest Code Provider" },
    DEPLOY_INFRA: { NAME: "deploy-infra", DESCRIPTION: "Deploy infrastructure contracts" },
    DEPLOY_REGISTRY: { NAME: "deploy-registry", DESCRIPTION: "Deploy Registry" },
    DEPLOY_RISK_MANAGER: { NAME: "deploy-risk-manager", DESCRIPTION: "Deploy Risk Manager" },
    DEPLOY_STRATEGY_PROVIDER: { NAME: "deploy-strategy-provider", DESCRIPTION: "Deploy Strategy Provider" },
    DEPLOY_VAULT: { NAME: "deploy-vault", DESCRIPTION: "Deploy Vault" },
    DEPLOY_VAULTS: { NAME: "deploy-vaults", DESCRIPTION: "Deploy all vault contracts" },
    DEPLOY_ODEFI_VAULT_BOOSTER: { NAME: "deploy-odefi-vault-booster", DESCRIPTION: "Deploy Odefi Vault Booster" },
  },
  ACTION_TASKS: {
    SET_MAX_DEPOSIT_MODE: { NAME: "set-max-deposit-mode", DESCRIPTION: "Set max deposit mode for adapter" },
    SET_MAX_DEPOSIT: { NAME: "set-max-deposit", DESCRIPTION: "Set max deposit amount for adapter" },
    APPROVE_ERC20: { NAME: "approve-erc20", DESCRIPTION: "Approve erc20 token" },
    BALANCE_OF: { NAME: "balance-of", DESCRIPTION: "Check token balance of address" },
    GET_ACTION: { NAME: "get-action", DESCRIPTION: "execute a get action in smart contract" },
    LIST_ACCOUNTS: { NAME: "list-accounts", DESCRIPTION: "Prints the list of accounts" },
    APPROVE_TOKEN: { NAME: "approve-token", DESCRIPTION: "Approve a token in Registry" },
    APPROVE_TOKENS: { NAME: "approve-tokens", DESCRIPTION: "Approve a list of tokens in Registry" },
    GET_BEST_STRATEGY: { NAME: "get-best-strategy", DESCRIPTION: "Get best strategy for a specific token" },
    MAP_LIQUIDITYPOOL_TO_ADAPTER: {
      NAME: "map-liquiditypool-to-adapter",
      DESCRIPTION: "Map a liquidity pool with a specific adapter",
    },
    MAP_LIQUIDITYPOOLS_TO_ADAPTER: {
      NAME: "map-liquiditypools-to-adapter",
      DESCRIPTION: "Map a list of liquidity pools with a specific adapter",
    },
    SET_BEST_STRATEGY: { NAME: "set-best-strategy", DESCRIPTION: "Set the best strategy for a specific token" },
    UNPAUSE_VAULT: { NAME: "unpause-vault", DESCRIPTION: "Set pause state for a specific vault" },
    VAULT_ACTIONS: {
      NAME: "vault-actions",
      DESCRIPTION: "Execute vault actions such as deposit, deposit with rebalance, etc",
    },
    ADD_RISK_PROFILE: { NAME: "add-risk-profile", DESCRIPTION: "Add a new risk profile" },
    GET_STRATEGY: { NAME: "get-strategy", DESCRIPTION: "Get the details of a specific strategy" },
  },
};
