/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVaultV3 } from "./IVaultV3";
export type { VaultV3 } from "./VaultV3";
export { VaultV3__factory } from "./factories/VaultV3__factory";
