/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IStrategyProviderV1Interface extends ethers.utils.Interface {
  functions: {
    "getRpToTokenToBestStrategy(uint256,bytes32)": FunctionFragment;
    "getRpToTokenToDefaultStrategy(uint256,bytes32)": FunctionFragment;
    "getVaultRewardTokenHashToVaultRewardTokenStrategy(bytes32)": FunctionFragment;
    "setBestDefaultStrategy(uint256,bytes32,tuple[])": FunctionFragment;
    "setBestStrategy(uint256,bytes32,tuple[])": FunctionFragment;
    "setVaultRewardStrategy(bytes32,(uint256,uint256))": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getRpToTokenToBestStrategy", values: [BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: "getRpToTokenToDefaultStrategy", values: [BigNumberish, BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getVaultRewardTokenHashToVaultRewardTokenStrategy",
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: "setBestDefaultStrategy",
    values: [BigNumberish, BytesLike, { pool: string; outputToken: string; isBorrow: boolean }[]],
  ): string;
  encodeFunctionData(
    functionFragment: "setBestStrategy",
    values: [BigNumberish, BytesLike, { pool: string; outputToken: string; isBorrow: boolean }[]],
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultRewardStrategy",
    values: [BytesLike, { hold: BigNumberish; convert: BigNumberish }],
  ): string;

  decodeFunctionResult(functionFragment: "getRpToTokenToBestStrategy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRpToTokenToDefaultStrategy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVaultRewardTokenHashToVaultRewardTokenStrategy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBestDefaultStrategy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBestStrategy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setVaultRewardStrategy", data: BytesLike): Result;

  events: {};
}

export class IStrategyProviderV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IStrategyProviderV1Interface;

  functions: {
    getRpToTokenToBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [
        ([string, string, boolean] & {
          pool: string;
          outputToken: string;
          isBorrow: boolean;
        })[],
      ]
    >;

    getRpToTokenToDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [
        ([string, string, boolean] & {
          pool: string;
          outputToken: string;
          isBorrow: boolean;
        })[],
      ]
    >;

    getVaultRewardTokenHashToVaultRewardTokenStrategy(
      _vaultRewardTokenHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[[BigNumber, BigNumber] & { hold: BigNumber; convert: BigNumber }]>;

    setBestDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setVaultRewardStrategy(
      _vaultRewardTokenHash: BytesLike,
      _vaultRewardStrategy: { hold: BigNumberish; convert: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  getRpToTokenToBestStrategy(
    _riskProfileCode: BigNumberish,
    _underlyingTokensHash: BytesLike,
    overrides?: CallOverrides,
  ): Promise<
    ([string, string, boolean] & {
      pool: string;
      outputToken: string;
      isBorrow: boolean;
    })[]
  >;

  getRpToTokenToDefaultStrategy(
    _riskProfileCode: BigNumberish,
    _underlyingTokensHash: BytesLike,
    overrides?: CallOverrides,
  ): Promise<
    ([string, string, boolean] & {
      pool: string;
      outputToken: string;
      isBorrow: boolean;
    })[]
  >;

  getVaultRewardTokenHashToVaultRewardTokenStrategy(
    _vaultRewardTokenHash: BytesLike,
    overrides?: CallOverrides,
  ): Promise<[BigNumber, BigNumber] & { hold: BigNumber; convert: BigNumber }>;

  setBestDefaultStrategy(
    _riskProfileCode: BigNumberish,
    _underlyingTokensHash: BytesLike,
    _strategySteps: { pool: string; outputToken: string; isBorrow: boolean }[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setBestStrategy(
    _riskProfileCode: BigNumberish,
    _underlyingTokensHash: BytesLike,
    _strategySteps: { pool: string; outputToken: string; isBorrow: boolean }[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setVaultRewardStrategy(
    _vaultRewardTokenHash: BytesLike,
    _vaultRewardStrategy: { hold: BigNumberish; convert: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    getRpToTokenToBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      ([string, string, boolean] & {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      })[]
    >;

    getRpToTokenToDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      ([string, string, boolean] & {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      })[]
    >;

    getVaultRewardTokenHashToVaultRewardTokenStrategy(
      _vaultRewardTokenHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[BigNumber, BigNumber] & { hold: BigNumber; convert: BigNumber }>;

    setBestDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: CallOverrides,
    ): Promise<void>;

    setBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: CallOverrides,
    ): Promise<void>;

    setVaultRewardStrategy(
      _vaultRewardTokenHash: BytesLike,
      _vaultRewardStrategy: { hold: BigNumberish; convert: BigNumberish },
      overrides?: CallOverrides,
    ): Promise<[BigNumber, BigNumber] & { hold: BigNumber; convert: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    getRpToTokenToBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getRpToTokenToDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getVaultRewardTokenHashToVaultRewardTokenStrategy(
      _vaultRewardTokenHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    setBestDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setVaultRewardStrategy(
      _vaultRewardTokenHash: BytesLike,
      _vaultRewardStrategy: { hold: BigNumberish; convert: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRpToTokenToBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getRpToTokenToDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getVaultRewardTokenHashToVaultRewardTokenStrategy(
      _vaultRewardTokenHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    setBestDefaultStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setBestStrategy(
      _riskProfileCode: BigNumberish,
      _underlyingTokensHash: BytesLike,
      _strategySteps: {
        pool: string;
        outputToken: string;
        isBorrow: boolean;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setVaultRewardStrategy(
      _vaultRewardTokenHash: BytesLike,
      _vaultRewardStrategy: { hold: BigNumberish; convert: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
