/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRiskManagerV2 } from "./IRiskManagerV2";
export type { RiskManagerV2 } from "./RiskManagerV2";
export { IRiskManagerV2__factory } from "./factories/IRiskManagerV2__factory";
