name: Earn protocol Install, lint, analyze and test pipeline

on:
  push:
    branches:
      - echidna

jobs:
  lint-compile-analyze-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        testName: -AdapterInvestmentLimitEchidnaTest
    
    env:
      MAINNET_NODE_URL: ${{ secrets.MAINNET_NODE_URL}}
      POLYGON_NODE_URL: ${{ secrets.POLYGON_NODE_URL}}
      COINMARKETCAP_API: ${{ secrets.COINMARKETCAP_API}}
      REPORT_GAS: true
      MNEMONIC: ${{ secrets.MNEMONIC}}
      STAGING_NETWORK_URL: ${{secrets.STAGING_NETWORK_URL}}
      STRATEGY_DIVISOR: 2
      MORALIS_APP_ID: ${{ secrets.MORALIS_APP_ID}}
      MORALIS_SERVER_URL: ${{ secrets.MORALIS_SERVER_URL}}

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
        with:
         token: ${{secrets.PAT}}
         submodules: recursive
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-v2-
      
      - name: Install
        run: |
          yarn install --frozen-lockfile
      
      - name: Lint
        run: |
          yarn lint
      
      - name: Compile
        run: |
          yarn compile
      
      - name: Optyfi-SDK Mainnet
        run: |
          yarn typechain && yarn optyfi-sdk:mainnet
      
      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: true
        id: slither
        with:
          node-version: 14
      
      - name: Test
        run: |
          yarn test-fast:mainnet
          yarn test-fast:vaultv2-upgrade-test:mainnet
          yarn test-fast:vaultv2-strategy:polygon
      
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
         payload: |
                {
                 "title": "Lint, Compile and Test",
                 "status": "${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }

      - name: Echidna
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip

      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.6.0/echidna-test-v1.6.0-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test
      
      - name: Run ${{ matrix.testName }}
        run: echidna-test . --contract ${{ matrix.testName }} --config echidna.config.yml