name: Earn protocol Install, lint, test and deploy pipeline

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x.x]
    
    env:
      MAINNET_NODE_URL: ${{ secrets.MAINNET_NODE_URL}}
      COINMARKETCAP_API: ${{ secrets.COINMARKETCAP_API}}
      MY_METAMASK_MNEMONIC: ${{ secrets.MY_METAMASK_MNEMONIC}}

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-v2-
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        if: always()
        with:
          name: Lint
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x.x]
    
    env:
      MAINNET_NODE_URL: ${{ secrets.MAINNET_NODE_URL}}
      COINMARKETCAP_API: ${{ secrets.COINMARKETCAP_API}}
      MY_METAMASK_MNEMONIC: ${{ secrets.MY_METAMASK_MNEMONIC}}

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-v2-
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Compile
        run: |
          yarn compile
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        if: always()
        with:
          name: Compile
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
  test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x.x]
    
    env:
      MAINNET_NODE_URL: ${{ secrets.MAINNET_NODE_URL}}
      COINMARKETCAP_API: ${{ secrets.COINMARKETCAP_API}}
      REPORT_GAS: true
      MY_METAMASK_MNEMONIC: ${{ secrets.MY_METAMASK_MNEMONIC}}
      STAGING_NETWORK_URL: ${{secrets.STAGING_NETWORK_URL}}

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-v2-
      - name: Add public IP to AWS security group
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: '22'
          to-port: '8545'
          protocol: 'tcp'
          description: 'GitHub Action'
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Deploy
        run: |
          yarn deploy-infra:staging
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        if: always()
        with:
          name: Test & Deploy
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
